[package]
name = "hbp"
version = "0.2.0"
edition = "2021"
description = "changwoolab's utilities for working without boilerplates"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
